### ISSUE TITLE
Image in the docs

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMetaTags#23]
I suggest to have an image like

[screenshot of semantic data in wiki] [arrow to the right] [screenshot of the html with the tags]

That allows people to see at a glance what it is about.

**Comment by kghbln** [comment]
I am not sure if this is really necessary. When it comes to SEO people suddenly start to get smart and understand things. :) 

However I would remove the example about the `smtgTagsBlacklist` setting from the README since people should actually leave this setting as is. Just noting that one should only change this if they know what they are doing is enough here I guess.

**Comment by JeroenDeDauw** [comment]
It is not really necessary of course. I do think it's be very nice to have. Disagree?

**Comment by thingles** [comment]
I tried doing this image using WikiApiary property page and a view source. The view source seemed way too small. I think something with the Semantic MediaWiki logo overlaid with a meta tag may work better.

**Comment by JeroenDeDauw** [comment]
@Cedricvdk Your awesome powerz are required for the greater good

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMetaTags#output-example
