### ISSUE TITLE
How do I set `og:image` etc. dynamically?

### ISSUE THREAD

**Issue by WMDRock** [SemanticMediaWiki/SemanticMetaTags#41]
This isn't really an issue: it's just a plea for help. I'm mostly trying to implement this to get a correct og:image to appear when pages are shared on Facebook. I've managed to follow the instructions and have a static image but I'm somewhat lost as to how to do variable meta properties.

If I could get some personalised help, I'm pretty sure I could help updated the documentation to provide a much better experience of trying to use what I can see is a very powerful addition to SMW.

### Setup and configuration

- SMW version: 2.5.4
- SMT version: 1.4.0
- MW version: 1.29.1
- DB (MySQL etc.):

**Comment by kghbln** [comment]
In "LocalSettings.php":
```
$smtgTagsStrings = [
        'og:site_name' => 'Semantic MediaWiki - Sandbox'
        ];
```
```
$smtgTagsProperties = [
        'og:image' => 'Meta element og-image',
        'og:image:type' => 'Meta element og-image-type',
        'og:image:width' => 'Meta element og-image-width',
        'og:image:height' => 'Meta element og-image-height'
        ];
```
On every wiki page you would have e.g. template {{SEOOG}} with:
```
{{#if:
 {{{PageImage|}}}
 |{{#set:
   |Meta element og-image={{#show: File:{{{PageImage|}}} |?Image-url }}
   |Meta element og-image-type={{#show: File:{{{PageImage|}}} |?Image-type }}
   |Meta element og-image-width={{#show: File:{{{PageImage|}}} |?Image-width }}
   |Meta element og-image-height={{#show: File:{{{PageImage|}}} |?Image-height }}
  }}
 |{{#set:
   |Meta element og-image=https://sandbox.semantic-mediawiki.org/w/SMWSandBoxLogo.png
   |Meta element og-image-type=image/png
   |Meta element og-image-width=142
   |Meta element og-image-height=142
  }}<!-- If no image definded for this page use standard values -->
}}
```
{{{PageImage|}}} would be added via a template {{PageImage}} if desired for that page:
```
{{{PageImage|}}}
```
What you still need to do is store the respective file related properties on the file pages using either the "Semantic Extra Special Properties" extension or the "MediaFunctions" extension.

You could also manually set the meta elements via the {{PageImage}} template without querying for the info.

It is indeed a bit of a fiddle. Perhaps there are other solutions too.

**Comment by WMDRock** [comment]
OK... I'm not feeling so bad about not having managed to sort this out on my own!

I'm going to look at some of the other SEO and Open Graph specific plugins, it might be they offer a better solution to this!

Thank you and you might consider dropping this advice into the readme file.

**Comment by kghbln** [comment]
Well hope is the last thing to die. I am not sure how other extensions could manage page specific images in a better way but still ...

**Comment by mwjames** [comment]
> OK... I'm not feeling so bad about not having managed to sort this out on my own!

Well, all you have to do is to create some template or manually method the create relevant annotations on each `File:` object using the syntax provided by SMW either as `{{#set: File name={{{FULLPAGENAME}}} }}` or `[[File name::{{{FULLPAGENAME}}}]]` etc. and this is independent from whether this SMT (i.e. SemanticMetaTags) is used or not!

For  example:

```
$smtgTagsProperties = [ 'description' => 'PropertyThatHoldsTheDescriptionCharateristics' ]
```

The sole purpose of SMT is to find content for tags customised which in above case means for the `description` meta tag to match and aggregate values from the `PropertyThatHoldsTheDescriptionCharateristics` property.

![image](https://user-images.githubusercontent.com/1245473/30374520-3472400e-98c0-11e7-96ce-f67b3b29c9b1.png)

> I'm going to look at some of the other SEO and Open Graph specific plugins, it might be they offer a better solution to this!

I'm going to imaging that those will not be integrated with SMW. The thing with this extension is that structured data from a subject (in MediaWiki terms an article) is transferred to meta tags as the one demonstrated above.

Other extensions may use something like `{{#meta: ... }}` directly on a page but that's not what we want here since those data are not structured and managed by SMW and you would need to add them on a per page basis either way.
