### ISSUE TITLE
SESP not working?

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMetaTags#9]
I’m using `'author' => 'Page author'` set by SESP and I cannot get the property to show up in the meta tags. Possibly because this is a fixed property?

**Comment by mwjames** [comment]
> SESP and I cannot get the property to show up in the meta tags. Possibly because this is a fixed property?

SMT fetches the data from the `ParserOutput` object to avoid having to read the `Store` or `DB` due to the hook being executed on each page view. By the time SESP is called the `ParserOutput` manipulating is no longer in scope of any operation (SESP injects the data directly to the Store using `SMWStore::updateDataBefore` hook which happens after `OutputPageParserOutput`) therefore the data set by SESP is not available in the `ParserOutput` object hence it can not be fetched by SMT.

[0] https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/src/Setup.php#L101

**Comment by JeroenDeDauw** [comment]
Guess the documentation should say something like "only properties defined in the wikitext of the page (for instance not those added by SESP)"

**Comment by JeroenDeDauw** [comment]
Has this been fixed by #20?

**Comment by thingles** [comment]
Just checked and it is not fixed.

**Comment by thingles** [comment]
Hold up — after a couple more reloads I see this now in my output!!!

`<meta name="author" content="Thingles,Paladox2016,MarkDilley,Kghbln" />`

It looks like it is fixed!

**Comment by thingles** [comment]
Yep, confirmed this is fixed.
